"""Alembic migration: Initial Phase 1 schema.

Manually authored initial migration (NOT autogenerated via alembic revision --autogenerate)
because we're creating the entire Phase 1 schema at once.

This migration is idempotent and safe to run multiple times (uses CREATE IF NOT EXISTS).

Includes all Phase 1 tables:
- organizations (root; no FK dependencies)
- properties (FK → organizations)
- units (FK → properties)
- incidents (FK → organizations, properties, units)

Plus proper constraints, indexes, and downgrade logic.

Execution order ensures FK constraints are satisfied:
1. Create UUID extension (pgcrypto preferred, fallback to uuid-ossp)
2. Create organizations (no FK dependencies)
3. Create properties (FK → organizations)
4. Create units (FK → properties)
5. Create incidents (FK → organizations, properties, units)
6. Create indexes for query performance

SECURITY-REVIEW: UUID extension creation requires superuser privileges.
- pgcrypto (preferred) may fail in managed databases (AWS RDS, Heroku, etc).
- Fallback to uuid-ossp; if both fail, migration explicitly raises error (no silent fallback).
- Supabase: pgcrypto is pre-installed; no manual action needed.
- Migration fails fast and clearly if UUID support is unavailable.

See README.md for runbook on UUID extension troubleshooting.

Revision ID: auto-generated by alembic revision command
Revises: None
Create Date: auto-generated by alembic revision command
"""
import logging

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.exc import ProgrammingError, OperationalError

logger = logging.getLogger(__name__)

# Revision identifiers
# This is a manually authored initial migration with a human-readable revision ID.
# Alembic accepts any unique string as a revision ID. "001_initial_phase1_schema"
# is intentional — it makes the migration history self-documenting.
# Do NOT change this ID once the migration has run in any environment.
revision = "001_initial_phase1_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create all Phase 1 tables with constraints and indexes.
    
    Execution order ensures FK constraints are satisfied:
    1. Create UUID generation extension (pgcrypto or uuid-ossp with explicit error on both failures)
    2. Create organizations (root; no FK dependencies)
    3. Create properties (FK → organizations)
    4. Create units (FK → properties)
    5. Create incidents (FK → organizations, properties, units)
    6. Create indexes for query performance
    
    Error Handling:
    - pgcrypto failure: log WARNING with exception details, attempt uuid-ossp
    - uuid-ossp failure: log ERROR with full traceback, explicitly raise to halt migration
    - Never silently continue without UUID support (breaks idempotency and data integrity)
    
    SECURITY-REVIEW: pgcrypto requires superuser in some managed DBs (RDS, Heroku, etc).
    This migration falls back to uuid-ossp if pgcrypto is unavailable.
    For Supabase: pgcrypto is pre-installed; no action needed.
    Pinned extension choice: pgcrypto is standard; uuid-ossp is explicit fallback only.
    Production must pre-install one extension; no runtime negotiation.
    """
    
    # ── Create UUID generation extension ──────────────────────────────────────
    # Try pgcrypto first (standard and preferred)
    uuid_ext_error_pgcrypto = None
    uuid_ext_error_uuid_ossp = None
    
    try:
        op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
        logger.info("✓ pgcrypto extension created successfully")
    except (ProgrammingError, OperationalError) as e:
        # pgcrypto unavailable — try uuid-ossp fallback (common in managed DBs)
        uuid_ext_error_pgcrypto = e
        logger.warning(
            f"⚠ pgcrypto extension creation failed "
            f"(likely: insufficient superuser privileges in managed database). "
            f"Error: {type(e).__name__}: {str(e)[:120]}. "
            f"Attempting fallback to uuid-ossp extension.",
            exc_info=True
        )
        try:
            op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
            logger.info("✓ uuid-ossp extension created as fallback")
        except (ProgrammingError, OperationalError) as e2:
            # Both extensions failed — cannot proceed. Explicitly raise error.
            uuid_ext_error_uuid_ossp = e2
            logger.error(
                f"✗ CRITICAL: Both UUID generation extensions failed. "
                f"pgcrypto error: {type(uuid_ext_error_pgcrypto).__name__}: "
                f"{str(uuid_ext_error_pgcrypto)[:100]}. "
                f"uuid-ossp error: {type(uuid_ext_error_uuid_ossp).__name__}: "
                f"{str(uuid_ext_error_uuid_ossp)[:100]}. "
                f"Database UUID support is unavailable. "
                f"ACTION REQUIRED: Manually create extension as database superuser, "
                f"or grant superuser privileges to migration user. "
                f"See README.md for UUID extension troubleshooting runbook.",
                exc_info=True
            )
            raise RuntimeError(
                f"Failed to create UUID generation extension. "
                f"Both pgcrypto and uuid-ossp are unavailable. "
                f"See logs for details. Aborting migration."
            ) from e2
    
    # ── Create organizations table (root; no FK dependencies) ───────────────
    op.create_table(
        'organizations',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug', name='uq_organizations_slug')
    )
    op.create_index('idx_organizations_slug', 'organizations', ['slug'], unique=True)
    op.create_index('idx_organizations_created_at', 'organizations', ['created_at'])
    logger.info("✓ organizations table created")
    
    # ── Create properties table (FK → organizations) ────────────────────────
    op.create_table(
        'properties',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('org_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('address', sa.String(length=512), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    )
    op.create_index('idx_properties_org_id', 'properties', ['org_id'])
    op.create_index('idx_properties_org_id_deleted_at', 'properties', ['org_id', 'deleted_at'])
    op.create_index('idx_properties_created_at', 'properties', ['created_at'])
    logger.info("✓ properties table created")
    
    # ── Create units table (FK → properties) ──────────────────────────────────
    op.create_table(
        'units',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('property_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('unit_number', sa.String(length=100), nullable=False),
        sa.Column('floor', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    )
    op.create_index('idx_units_property_id', 'units', ['property_id'])
    op.create_index('idx_units_property_id_deleted_at', 'units', ['property_id', 'deleted_at'])
    op.create_index('idx_units_created_at', 'units', ['created_at'])
    logger.info("✓ units table created")
    
    # ── Create incidents table (FK → organizations, properties, units) ──────
    op.create_table(
        'incidents',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('org_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('property_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('unit_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='OPEN'),
        sa.Column('priority', sa.String(length=50), nullable=False, server_default='MEDIUM'),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
        sa.CheckConstraint("status IN ('OPEN', 'PENDING_APPROVAL', 'RESOLVED', 'CLOSED')", name='ck_incidents_status'),
        sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_incidents_priority'),
    )
    op.create_index('idx_incidents_org_id', 'incidents', ['org_id'])
    op.create_index('idx_incidents_org_id_status', 'incidents', ['org_id', 'status'])
    op.create_index('idx_incidents_property_id', 'incidents', ['property_id'])
    op.create_index('idx_incidents_unit_id', 'incidents', ['unit_id'])
    op.create_index('idx_incidents_org_id_deleted_at', 'incidents', ['org_id', 'deleted_at'])
    op.create_index('idx_incidents_created_at', 'incidents', ['created_at'])
    logger.info("✓ incidents table created")
    
    logger.info("✓ Migration upgrade() completed: all Phase 1 tables created successfully")


def downgrade() -> None:
    """Drop all Phase 1 tables in reverse order (respecting FK constraints).
    
    Downgrade order is reverse of upgrade:
    1. Drop incidents (has FK dependencies)
    2. Drop units (has FK to properties)
    3. Drop properties (has FK to organizations)
    4. Drop organizations (root)
    
    Note: UUID extensions are NOT dropped (safe to leave; used by other schemas/apps).
    """
    logger.info("Beginning Phase 1 schema downgrade...")
    
    # Drop in reverse FK dependency order
    op.drop_table('incidents')
    logger.info("✓ incidents table dropped")
    
    op.drop_table('units')
    logger.info("✓ units table dropped")
    
    op.drop_table('properties')
    logger.info("✓ properties table dropped")
    
    op.drop_table('organizations')
    logger.info("✓ organizations table dropped")
    
    logger.info("✓ Migration downgrade() completed: all Phase 1 tables dropped successfully")
