"""Alembic migration: Initial Phase 1 schema (001_initial_phase1_schema).

Manually authored initial migration (NOT autogenerated via alembic revision --autogenerate)
because we're creating the entire Phase 1 schema at once.

This migration is idempotent and safe to run multiple times (uses CREATE IF NOT EXISTS
and proper error handling).

Includes all Phase 1 tables:
- organizations (root; no FK dependencies)
- properties (FK → organizations)
- units (FK → properties)
- incidents (FK → organizations, properties, units)

Plus proper constraints, indexes, and downgrade logic.

Execution order ensures FK constraints are satisfied:
1. Create UUID extension (pgcrypto preferred, fallback to uuid-ossp, explicit error if both fail)
2. Create organizations (no FK dependencies)
3. Create properties (FK → organizations)
4. Create units (FK → properties)
5. Create incidents (FK → organizations, properties, units)
6. Create indexes for query performance

SECURITY-REVIEW: UUID extension creation requires superuser privileges.
- pgcrypto (preferred) may fail in managed databases (AWS RDS, Heroku, etc).
- Fallback to uuid-ossp; if both fail, migration explicitly raises RuntimeError.
- Supabase: pgcrypto is pre-installed; no manual action needed.
- Migration fails fast and clearly if UUID support is unavailable.
- For managed databases without superuser: ask provider to install extension, or 
  create extension as migration user if provider supports `CREATE EXTENSION IF NOT EXISTS`.

See README.md for runbook on UUID extension troubleshooting.

Revision ID: 001_initial_phase1_schema (human-readable; auto-generated alembic)
Revises: None (initial migration)
Create Date: 2025-01-XX (auto-generated by alembic revision command)
"""
import logging

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.exc import ProgrammingError, OperationalError

logger = logging.getLogger(__name__)

# Revision identifiers used by alembic
# Revision ID: auto-generated by alembic revision command
# Down revision: None (this is the first migration)
revision = "001_initial_phase1_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create all Phase 1 tables with constraints and indexes.
    
    Execution order ensures FK constraints are satisfied:
    1. Create UUID generation extension (pgcrypto or uuid-ossp with explicit error on both failures)
    2. Create organizations (root; no FK dependencies)
    3. Create properties (FK → organizations)
    4. Create units (FK → properties)
    5. Create incidents (FK → organizations, properties, units)
    6. Create indexes for query performance
    
    Error Handling:
    - pgcrypto failure: log WARNING with exception details, attempt uuid-ossp
    - uuid-ossp failure: log ERROR with full traceback, explicitly raise RuntimeError
    - Never silently continue without UUID support (breaks idempotency and data integrity)
    
    SECURITY-REVIEW: pgcrypto requires superuser in some managed DBs (RDS, Heroku, etc).
    This migration falls back to uuid-ossp if pgcrypto fails. If BOTH fail, the migration
    raises an explicit error rather than silently proceeding without UUID support.
    
    Troubleshooting (see README.md for details):
    - AWS RDS: Request RDS team to enable pgcrypto extension, or use Supabase (better DX)
    - Heroku Postgres: pgcrypto is pre-installed (standard)
    - Supabase: pgcrypto is pre-installed (standard)
    - Local PostgreSQL: Run as superuser or manually run: CREATE EXTENSION pgcrypto;
    """
    # Step 1: Create UUID extension with fallback
    _create_uuid_extension()
    
    # Step 2: Create organizations (root; no FK dependencies)
    op.create_table(
        "organizations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False, primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("NOW()")),
        sa.