"""Alembic migration: Initial Phase 1 schema.

Manually authored initial migration (NOT autogenerated via alembic revision --autogenerate).
Creates the entire Phase 1 schema in a single migration for atomic deployment.

Includes all Phase 1 tables:
  - organizations (root; no FK dependencies)
  - properties    (FK -> organizations)
  - units         (FK -> properties)
  - incidents     (FK -> organizations, properties, units)

Plus composite indexes for query performance and a complete downgrade() for safe rollback.

Execution order respects FK constraints:
  1. UUID extension (pgcrypto preferred, uuid-ossp fallback, explicit error if both fail)
  2. organizations
  3. properties
  4. units
  5. incidents
  6. indexes

SECURITY: UUID extension creation requires superuser in some managed databases
  (AWS RDS, Heroku). This migration falls back to uuid-ossp if pgcrypto is unavailable,
  and raises a clear RuntimeError if both fail. Never silently continues without UUID support.

  Supabase: pgcrypto pre-installed. AWS RDS: request extension via RDS console.
  Local PostgreSQL: run as superuser or: CREATE EXTENSION IF NOT EXISTS pgcrypto;

Revision ID : 001_initial_phase1_schema  (human-readable; manually authored)
Revises     : None (this is the first migration)
Create Date : 2026-05-25
"""
import logging

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.exc import ProgrammingError, OperationalError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Revision identifiers — used by Alembic to track migration history.
# revision is intentionally a human-readable string (Alembic accepts any
# unique string, not only hex UUIDs). Do NOT change once deployed.
# ---------------------------------------------------------------------------
revision = "001_initial_phase1_schema"
down_revision = None
branch_labels = None
depends_on = None


def _create_uuid_extension() -> None:
    """Create UUID generation extension with pgcrypto -> uuid-ossp fallback.

    Error handling:
    - pgcrypto failure: logs WARNING, attempts uuid-ossp
    - uuid-ossp failure: logs ERROR, raises RuntimeError (migration cannot proceed)
    - Unknown exceptions: re-raised immediately (never swallowed silently)
    """
    try:
        op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
        logger.info("migration: pgcrypto extension created/verified")
        return
    except (ProgrammingError, OperationalError) as pgcrypto_err:
        logger.warning(
            "migration: pgcrypto unavailable (%s: %s) — trying uuid-ossp fallback",
            type(pgcrypto_err).__name__, str(pgcrypto_err)[:120],
        )
    # pgcrypto failed — try uuid-ossp
    try:
        op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
        logger.info("migration: uuid-ossp extension created/verified as fallback")
    except (ProgrammingError, OperationalError) as uuid_err:
        logger.error(
            "migration: CRITICAL — both pgcrypto and uuid-ossp unavailable. "
            "uuid-ossp error: %s: %s. "
            "ACTION REQUIRED: grant superuser or pre-install extension. "
            "See README.md for UUID extension troubleshooting.",
            type(uuid_err).__name__, str(uuid_err)[:120],
        )
        raise RuntimeError(
            "Cannot create UUID extension. Both pgcrypto and uuid-ossp are unavailable. "
            "See migration logs for details."
        ) from uuid_err


def upgrade() -> None:
    """Create all Phase 1 tables with constraints and indexes."""

    # 1. UUID extension ────────────────────────────────────────────────────
    _create_uuid_extension()

    # 2. organizations (root; no FK dependencies) ──────────────────────────
    op.create_table(
        "organizations",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), nullable=False,
            server_default=sa.text("gen_random_uuid()"), primary_key=True,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(100), nullable=False),
        sa.Column("email_domain", sa.String(255), nullable=True),
        sa.Column("plan", sa.String(50), nullable=False, server_default="beta"),
        sa.Column("unit_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.UniqueConstraint("slug", name="uq_organizations_slug"),
    )
    op.create_index("idx_organizations_slug", "organizations", ["slug"], unique=True)
    op.create_index("idx_organizations_email_domain", "organizations", ["email_domain"])
    op.create_index("idx_organizations_created_at", "organizations", ["created_at"])
    op.create_index(
        "idx_organizations_deleted",
        "organizations",
        ["deleted_at"],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    logger.info("migration: organizations table created")

    # 3. properties (FK -> organizations) ──────────────────────────────────
    op.create_table(
        "properties",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), nullable=False,
            server_default=sa.text("gen_random_uuid()"), primary_key=True,
        ),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("address", sa.String(512), nullable=True),
        sa.Column("city", sa.String(100), nullable=True),
        sa.Column("state", sa.String(100), nullable=True),
        sa.Column("postal_code", sa.String(20), nullable=True),
        sa.Column("country", sa.String(100), nullable=True),
        sa.Column("unit_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="RESTRICT"),
    )
    op.create_index("idx_properties_org_id", "properties", ["org_id"])
    op.create_index(
        "idx_properties_org_id_active",
        "properties",
        ["org_id", "deleted_at"],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("idx_properties_created_at", "properties", ["created_at"])
    logger.info("migration: properties table created")

    # 4. units (FK -> properties) ──────────────────────────────────────────
    op.create_table(
        "units",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), nullable=False,
            server_default=sa.text("gen_random_uuid()"), primary_key=True,
        ),
        sa.Column("property_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("unit_number", sa.String(50), nullable=False),
        sa.Column("floor", sa.String(50), nullable=True),
        sa.Column("tenant_name", sa.String(255), nullable=True),
        sa.Column("tenant_email", sa.String(255), nullable=True),
        sa.Column("tenant_phone", sa.String(50), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="RESTRICT"),
        sa.UniqueConstraint("property_id", "unit_number", name="uq_units_property_unit"),
    )
    op.create_index("idx_units_property_id", "units", ["property_id"])
    op.create_index(
        "idx_units_property_id_active",
        "units",
        ["property_id", "deleted_at"],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("idx_units_tenant_email", "units", ["tenant_email"])
    op.create_index("idx_units_created_at", "units", ["created_at"])
    logger.info("migration: units table created")

    # 5. incidents (FK -> organizations, properties, units) ────────────────
    op.create_table(
        "incidents",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), nullable=False,
            server_default=sa.text("gen_random_uuid()"), primary_key=True,
        ),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("property_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("unit_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "thread_id", postgresql.UUID(as_uuid=True), nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("urgency", sa.String(50), nullable=True),
        sa.Column(
            "status", sa.String(50), nullable=False, server_default="OPEN",
        ),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column("source_channel", sa.String(50), nullable=True),
        sa.Column("source_address", sa.String(255), nullable=True),
        sa.Column("raw_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="SET NULL"),
        sa.CheckConstraint(
            "status IN ('OPEN','PENDING_APPROVAL','RESOLVED','CLOSED')",
            name="ck_incidents_status",
        ),
    )
    op.create_index("idx_incidents_org_id", "incidents", ["org_id"])
    op.create_index("idx_incidents_org_id_status", "incidents", ["org_id", "status"])
    op.create_index("idx_incidents_urgency_status", "incidents", ["urgency", "status"])
    op.create_index("idx_incidents_thread_id", "incidents", ["thread_id"])
    op.create_index("idx_incidents_property_id", "incidents", ["property_id"])
    op.create_index("idx_incidents_unit_id", "incidents", ["unit_id"])
    op.create_index("idx_incidents_created_at", "incidents", ["created_at"])
    logger.info("migration: incidents table created")

    logger.info("migration: upgrade() complete — all Phase 1 tables created")


def downgrade() -> None:
    """Drop all Phase 1 tables in reverse FK dependency order.

    Drop order (reverse of upgrade):
      1. incidents  — depends on organizations, properties, units
      2. units      — depends on properties
      3. properties — depends on organizations
      4. organizations — root

    Note: UUID extensions (pgcrypto / uuid-ossp) are NOT dropped.
    Dropping shared extensions could break other schemas/apps in the same DB.
    """
    logger.info("migration: downgrade() starting — dropping Phase 1 tables")

    op.drop_table("incidents")
    logger.info("migration: incidents dropped")

    op.drop_table("units")
    logger.info("migration: units dropped")

    op.drop_table("properties")
    logger.info("migration: properties dropped")

    op.drop_table("organizations")
    logger.info("migration: organizations dropped")

    logger.info("migration: downgrade() complete — all Phase 1 tables removed")
