"""Alembic migration: Add tenants and units tables.

Manually authored initial migration (NOT autogenerated via alembic revision --autogenerate).
Creates the tenants and units tables for multi-tenant management.

Includes indexes on foreign keys and columns used in WHERE/ORDER BY.
SECURITY: No security-sensitive operations are performed in this migration.

Revision ID : 002_add_tenants_units
Revises     : 001_initial_phase1_schema
Create Date : 2025-01-16 (add tenants and units tables)
"""
import logging

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

logger = logging.getLogger(__name__)

# Step 1: Create tenants table
op.create_table(
    "tenants",
    sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
    sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False, comment="Foreign key to organizations.id"),
    sa.Column("name", sa.String(255), nullable=False),
    sa.Column("email", sa.String(255), unique=True, comment="Unique email per organization"),
    sa.Column("phone", sa.String(100)),
    sa.Column("unit_id", postgresql.UUID(as_uuid=True), nullable=True, comment="Foreign key to units.id"),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id")
)
op.create_index(op.f("ix_tenants_org_id"), "tenants", ["org_id"], unique=False)

# Step 2: Create units table
op.create_table(
    "units",
    sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
    sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False, comment="Foreign key to organizations.id"),
    sa.Column("label", sa.String(255), nullable=False),
    sa.Column("address", sa.Text(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id")
)
op.create_index(op.f("ix_units_org_id"), "units", ["org_id"], unique=False)

# Step 3: Create indexes on foreign keys and columns used in WHERE/ORDER BY
op.create_index(op.f("ix_tenants_unit_id"), "tenants", ["unit_id"], unique=False)
op.create_index(op.f("ix_units_label"), "units", ["label"], unique=False)