"""Alembic migration: Add organisations table.

Manually authored initial migration (NOT autogenerated via alembic revision --autogenerate).
Creates the organisations table for multi-tenant org isolation.

Includes indexes for query performance and a complete downgrade() for safe rollback.

Execution order respects FK constraints:
  1. UUID extension (pgcrypto preferred, uuid-ossp fallback, explicit error if both fail)
  2. organisations
  3. indexes

SECURITY: UUID extension creation requires superuser in some managed databases
  (AWS RDS, Heroku). This migration falls back to uuid-ossp if pgcrypto is unavailable,
  and raises a clear RuntimeError if both fail. Never silently continues without UUID support.

  Supabase: pgcrypto pre-installed. AWS RDS: request extension via RDS console.
  Local PostgreSQL: run as superuser or: CREATE EXTENSION IF NOT EXISTS pgcrypto;

Revision ID : 003_add_orgs
Revises     : 002
Create Date : 2025-01-16 (add organisations table)
"""
import logging

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.exc import ProgrammingError, OperationalError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Revision identifiers — used by Alembic to track migration history.
# revision is intentionally a human-readable string (Alembic accepts any
# unique string, not only hex UUIDs). Do NOT change once deployed.
# ---------------------------------------------------------------------------
revision = "003_add_orgs"
down_revision = "002"
branch_labels = None
depends_on = None


def _create_uuid_extension() -> None:
    """Create UUID generation extension with pgcrypto -> uuid-ossp fallback.

    Error handling:
    - pgcrypto failure: logs WARNING, attempts uuid-ossp
    - uuid-ossp failure: logs ERROR, raises RuntimeError (migration cannot proceed)
    - Unknown exceptions: re-raised immediately (never swallowed silently)
    
    SECURITY-REVIEW: This function is critical for schema integrity. Every error path
    is explicitly logged and unrecoverable failures raise RuntimeError to halt migration.
    No silent failures are possible — if both UUID extensions fail, the migration stops.
    """
    try:
        op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
        logger.info("migration: pgcrypto extension created/verified")
        return
    except (ProgrammingError, OperationalError) as pgcrypto_err:
        logger.warning(
            "migration: pgcrypto unavailable (%s: %s) — trying uuid-ossp fallback",
            type(pgcrypto_err).__name__, str(pgcrypto_err)[:120],
        )
    
    # pgcrypto failed — try uuid-ossp
    try:
        op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
        logger.info("migration: uuid-ossp extension created/verified as fallback")
        return
    except (ProgrammingError, OperationalError) as uuid_err:
        logger.error(
            "migration: CRITICAL — both pgcrypto and uuid-ossp unavailable (%s: %s). "
            "Schema cannot be created without UUID support.",
            type(uuid_err).__name__, str(uuid_err)[:120],
        )
        raise RuntimeError(
            "UUID extension (pgcrypto or uuid-ossp) is required but unavailable. "
            "Check database permissions and extension availability."
        ) from uuid_err
    except Exception as unknown_err:
        # Re-raise any unexpected exception immediately (never swallow)
        logger.error("migration: Unexpected error during UUID extension setup: %s", unknown_err, exc_info=True)
        raise


def upgrade() -> None:
    """Apply organisations table and indexes."""
    
    # Step 1: Create UUID extension (with fallback and error handling)
    _create_uuid_extension()
    
    # Step 2: Create organisations table
    op.create_table(
        "organisations",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("imap_host", sa.String(255)),
        sa.Column("imap_port", sa.Integer, default=993),
        sa.Column("imap_username", sa.String(255)),
        sa.Column("imap_password_enc", sa.String(255)),  # Fernet encrypted
        sa.Column("smtp_host", sa.String(255)),
        sa.Column("smtp_port", sa.Integer, default=587),
        sa.Column("polling_active", sa.Boolean, default=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True)),
        sa.PrimaryKeyConstraint("id"),
    )
    
    # Step 3: Create indexes
    op.create_index("idx_organisations_deleted", "organisations", ["deleted_at"], unique=False)

def downgrade() -> None:
    """Downgrade to previous state."""
    op.drop_index("idx_organisations_deleted", table_name="organisations")
    op.drop_table("organisations")